//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by UCMC_EducationKit.rc
//
#define IDC_FILEOPEN                    3
#define IDC_FILESAVE                    4
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_UCMC_EDUCATIONKIT_DIALOG    102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG1                     129
#define IDC_UART_COMBO                  1000
#define IDC_UART_OPEN_BTN               1001
#define IDC_RESET                       1008
#define IDC_INIT                        1009
#define IDC_ENABLE                      1010
#define IDC_DISABLE                     1011
#define IDC_STOP                        1012
#define IDC_HOME                        1013
#define IDC_CLEAR                       1014
#define IDC_STATUS                      1015
#define IDC_ERROR                       1016
#define IDC_STATIC_STATUS               1017
#define IDC_STATIC_ERROR                1018
#define IDC_STATIC_DEVICE_ERROR         1019
#define IDC_DEV_ERROR                   1020
#define IDC_STATIC_GET_CUR_CONTCUR      1021
#define IDC_STATIC_GET_CUR_OUTPUTCUR    1022
#define IDC_STATIC_GET_CUR_P_GAIN       1023
#define IDC_STATIC_GET_CUR_I_GAIN       1024
#define IDC_STATIC_GET_CUR_TARGET       1025
#define IDC_STATIC_GET_CUR_ACTUAL       1026
#define IDC_STATIC_GET_VEL_ENCPULSNUM   1027
#define IDC_STATIC_GET_VEL_ACCEL        1028
#define IDC_STATIC_GET_VEL_P_GAIN       1029
#define IDC_STATIC_GET_VEL_I_GAIN       1030
#define IDC_STATIC_GET_VEL_TARGET_RPM   1031
#define IDC_STATIC_GET_VEL_ACTUAL_RPM   1032
#define IDC_STATIC_VERSION              1033
#define IDC_EDIT_CUR_CONT               1034
#define IDC_BUTTON_CUR_CONT             1035
#define IDC_EDIT_CUR_OUTPUT             1036
#define IDC_BUTTON_CUR_OUTPUT           1037
#define IDC_EDIT_CUR_P_GAIN             1038
#define IDC_BUTTON_CUR_P_GAIN           1039
#define IDC_EDIT_CUR_I_GAIN             1040
#define IDC_BUTTON_CUR_I_GAIN           1041
#define IDC_EDIT_CUR_TARGET             1042
#define IDC_BUTTON_CUR_TARGET           1043
#define IDC_SEND_ARRAY                  1044
#define IDC_STATIC_GET_POS_P_GAIN       1045
#define IDC_STATIC_GET_POS_P_GAIN2      1045
#define IDC_IMAGE                       1045
#define IDC_STATIC_GET_POS_I_GAIN       1046
#define IDC_DLG_IMAGE                   1046
#define IDC_STATIC_GET_POS_D_GAIN       1047
#define IDC_MAKE                        1047
#define IDC_STATIC_GET_POS_NEG_LIMIT    1048
#define IDC_TEST                        1048
#define IDC_STATIC_GET_POS_POS_LIMIT    1049
#define IDC_BUTTON2                     1049
#define IDC_MAKE_STEP                   1049
#define IDC_STATIC_GET_POS_TARGET       1050
#define IDC_BUTTON3                     1050
#define IDC_MAKE_PARA                   1050
#define IDC_STATIC_GET_POS_ACTUAL       1051
#define IDC_BUTTON1                     1051
#define IDC_STATIC_GET_POS_ABS          1052
#define IDC_TEST2                       1052
#define IDC_UP_BOTTON                   1052
#define IDC_STATIC_GET_POS_ABS_ANGLE    1053
#define IDC_TEST3                       1053
#define IDC_TEST4                       1054
#define IDC_EDIT_VEL_ENCPULSE           1055
#define IDC_BUTTON_VEL_ENCPULSE         1056
#define IDC_EDIT_VEL_ACCEL              1057
#define IDC_BUTTON_VEL_ACCEL            1058
#define IDC_EDIT_VEL_P_GAIN             1059
#define IDC_BUTTON_VEL_P_GAIN           1060
#define IDC_EDIT_VEL_I_GAIN             1061
#define IDC_BUTTON_VEL_I_GAIN           1062
#define IDC_EDIT_VEL_TARGET             1063
#define IDC_BUTTON_VEL_TARGET           1064
#define IDC_EDIT_VEL_MAXVEL             1065
#define IDC_BUTTON_VEL_MAXVEL           1066
#define IDC_EDIT_POS_P_GAIN             1067
#define IDC_BUTTON_POS_P_GAIN           1068
#define IDC_EDIT_POS_I_GAIN             1069
#define IDC_BUTTON_POS_I_GAIN           1070
#define IDC_EDIT_POS_D_GAIN             1071
#define IDC_BUTTON_POS_D_GAIN           1072
#define IDC_EDIT_POS_NEGATIVE           1073
#define IDC_BUTTON_POS_NEGATIVE         1074
#define IDC_EDIT_POS_POSITIVE           1075
#define IDC_BUTTON_POS_POSITIVE         1076
#define IDC_EDIT_POS_TRAGET             1077
#define IDC_BUTTON_POS_TARGET           1078
#define IDC_EDIT_POS_ACTUAL             1079
#define IDC_BUTTON_POS_ACTUAL           1080
#define IDC_SEND_ALL_VALUE              1081
#define IDC_EDIT_RAMP                   1081
#define IDC_SHOW_GRAPH                  1082
#define IDC_SAMPLING_EIDT               1083
#define IDC_EDIT_STEP                   1083
#define IDC_POSITION_EDIT               1084
#define IDC_MAKE_SINE                   1084
#define IDC_DOWN_BUTTON                 1085
#define IDC_EDIT_SINE                   1085
#define IDC_TAB2                        1087
#define IDC_RADIO_VEL                   1091
#define IDC_RADIO_POSITION              1092
#define IDC_RADIO_FB                    1093
#define IDC_RADIO_FF1                   1094
#define IDC_RADIO_FF2                   1095
#define IDC_RADIO_GRAPH_POS             1099
#define IDC_RADIO_GRAPH_VEL             1100
#define IDC_RADIO_GRAPH_ERR             1101
#define IDC_EDIT_FF1                    1102
#define IDC_SAMPLINGNUM                 1103
#define IDC_EDIT_FF2                    1104
#define IDC_SLIDER2                     1106

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1107
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
